services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_db"]
      interval: 30s
      timeout: 10s
      retries: 5
  migrations:
    build: ./backend
    env_file:
      - ./backend/.env
    command: >
      sh -c 'dockerize -wait tcp://db:5432 -timeout 60s &&
            python manage.py migrate &&
            echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(\"$$ADMIN_USERNAME\", \"$$ADMIN_EMAIL\", \"$$ADMIN_PASSWORD\") if not User.objects.filter(username=\"$$ADMIN_USERNAME\").exists() else 0" | python manage.py shell'
    volumes:
      - ./backend:/app
    depends_on:
      - db
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
volumes:
  postgres_data:
