services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Fc00224200"
  migrations:
    build: ./backend
    command: python manage.py migrate
    volumes:
      - ./backend:/app
    depends_on:
      - db
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
volumes:
  postgres_data:
