# Generated by Django 4.2.6 on 2023-10-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
