# Generated by Django 4.2.6 on 2023-10-28 12:48

from django.db import migrations, models


def create_initial_categories(apps, schema_editor):
    ProductCategory = apps.get_model("product_category", "ProductCategory")
    categories_data = [
        {"name": "Smartphones", "discount": 2.55},
        {"name": "Furniture", "discount": 3},
        {"name": "Electronics", "discount": 4.3},
        {"name": "Appliances", "discount": 5},
        {"name": "Regrigerators", "discount": 7.5},
    ]

    for category_info in categories_data:
        ProductCategory.objects.create(**category_info)


class Migration(migrations.Migration):
    dependencies = [
        ("product_category", "0002_alter_productcategory_table"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
